name: "Synchronize Coverity Scan branch"

on:
  schedule:
    - cron: "7 3 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync coverity_scan branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: |
          git checkout -b coverity_scan origin/master
          git push --force origin coverity_scan
